In [68]:
import numpy as np

In [69]:
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)

int64


In [70]:
arr_float = np.array([1.0, 2.0, 3.0])
print(arr_float.dtype == np.float64)

True


In [71]:
arr_complex = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print("3. Complex array:", arr_complex, "dtype:", arr_complex.dtype)

3. Complex array: [1.+2.j 3.+4.j 5.+6.j] dtype: complex128


In [72]:
arr_int = np.array([1, 2, 3, 4, 5])
arr_float32 = arr_int.astype(np.float32)
print("4. Float32 array:", arr_float32, "dtype:", arr_float32.dtype)

4. Float32 array: [1. 2. 3. 4. 5.] dtype: float32


In [73]:
arr_float64 = np.array([1.0, 2.0, 3.0], dtype=np.float64)
arr_float32 = arr_float64.astype(np.float32)
print("5. Converted to float32:", arr_float32, "dtype:", arr_float32.dtype)

5. Converted to float32: [1. 2. 3.] dtype: float32


In [74]:
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype
print("6. Array attributes:", array_attributes(np.array([[1, 2], [3, 4]])))


6. Array attributes: ((2, 2), 4, dtype('int64'))


In [75]:
def array_dimension(arr):
    return arr.ndim
print("7. Array dimension:", array_dimension(np.array([[1, 2], [3, 4]])))

7. Array dimension: 2


In [76]:
def item_size_info(arr):
    return arr.itemsize, arr.nbytes
print("8. Item size and total size:", item_size_info(np.array([1, 2, 3])))

8. Item size and total size: (8, 24)


In [77]:
def array_strides(arr):
    return arr.strides
print("9. Array strides:", array_strides(np.array([[1, 2], [3, 4]])))

9. Array strides: (16, 8)


In [78]:
def shape_strides_relationship(arr):
    return arr.shape, arr.strides
print("10. Shape and strides:", shape_strides_relationship(np.array([[1, 2], [3, 4]])))


10. Shape and strides: ((2, 2), (16, 8))


In [79]:
def create_zeros_array(n):
    return np.zeros(n)
print("11. Zeros array:", create_zeros_array(5))


11. Zeros array: [0. 0. 0. 0. 0.]


In [80]:
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))
print("12. Ones matrix:", create_ones_matrix(2, 3))


12. Ones matrix: [[1. 1. 1.]
 [1. 1. 1.]]


In [81]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)
print("13. Range array:", generate_range_array(0, 10, 2))


13. Range array: [0 2 4 6 8]


In [82]:
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)
print("14. Linear space:", generate_linear_space(0, 1, 5))


14. Linear space: [0.   0.25 0.5  0.75 1.  ]


In [83]:
def create_identity_matrix(n):
    return np.eye(n)
print("15. Identity matrix:", create_identity_matrix(3))


15. Identity matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [84]:
def list_to_array(py_list):
    return np.array(py_list)
print("16. List to array:", list_to_array([1, 2, 3]))


16. List to array: [1 2 3]


In [85]:
arr = np.array([1, 2, 3, 4])
arr_view = arr.view()
print("17. Original array:", arr, "View:", arr_view)

17. Original array: [1 2 3 4] View: [1 2 3 4]


In [86]:
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)
print("18. Concatenated array:", concatenate_arrays(np.array([1, 2]), np.array([3, 4])))


18. Concatenated array: [1 2 3 4]


In [87]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5], [6]])
print("19. Horizontal concatenation:", np.hstack((arr1, arr2)))


19. Horizontal concatenation: [[1 2 5]
 [3 4 6]]


In [88]:
arr = np.array([0, 1, 2, 3, 4, 5])
print("26. 3rd element:", arr[2])

26. 3rd element: 2


In [89]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("27. Element at (1,2):", arr_2d[1, 2])

27. Element at (1,2): 6


In [90]:
arr = np.array([1, 6, 3, 7, 2, 8])
print("28. Elements > 5:", arr[arr > 5])

28. Elements > 5: [6 7 8]


In [91]:
print("29. Slice [2:6]:", arr[2:6])

29. Slice [2:6]: [3 7 2 8]


In [92]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("30. Sub-array:", arr_2d[0:2, 1:3])

30. Sub-array: [[2 3]
 [5 6]]


In [93]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
indices = np.array([[0, 0], [1, 2]])
print("31. Elements at indices:", arr_2d[indices[:, 0], indices[:, 1]])

31. Elements at indices: [1 6]


In [94]:
arr = np.array([1, 6, 3, 7, 2, 8])
threshold = 5
print("32. Elements > threshold:", arr[arr > threshold])

32. Elements > threshold: [6 7 8]


In [95]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
indices = (np.array([0, 1]), np.array([0, 1]), np.array([0, 1]))
print("33. 3D array elements:", arr_3d[indices])

33. 3D array elements: [1 8]


In [96]:
arr = np.array([1, 6, 3, 7, 2, 8])
print("34. Elements > 3 and < 7:", arr[(arr > 3) & (arr < 7)])

34. Elements > 3 and < 7: [6]


In [97]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
row_indices = np.array([0, 1])
col_indices = np.array([1, 2])
print("35. Elements at indices:", arr_2d[row_indices, col_indices])

35. Elements at indices: [2 6]


In [98]:
arr = np.array([1, 2, 3])
print("36. Add scalar 5:", arr + 5)

36. Add scalar 5: [6 7 8]


In [99]:
arr_3x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_1x3 = np.array([[1, 2, 3]])
print("37. Row multiplication:", arr_3x4 * arr_1x3.T)

37. Row multiplication: [[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


In [100]:
arr_4x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr_1x4 = np.array([[1, 2, 3, 4]])
print("38. Broadcasting addition:", arr_4x3 + arr_1x4.T)

38. Broadcasting addition: [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [101]:
arr_3x1 = np.array([[1], [2], [3]])
arr_1x3 = np.array([[4, 5, 6]])
print("39. Broadcasting addition:", arr_3x1 + arr_1x3)

39. Broadcasting addition: [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [102]:
arr_2x3 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2x2 = np.array([[1, 2], [3, 4]])
try:
    print(arr_2x3 * arr_2x2)
except ValueError as e:
    print("40. Shape incompatibility error:", str(e))


40. Shape incompatibility error: operands could not be broadcast together with shapes (2,3) (2,2) 


In [103]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("41. Column-wise mean:", np.mean(arr_2d, axis=0))

41. Column-wise mean: [2.5 3.5 4.5]


In [104]:
print("42. Row-wise max:", np.max(arr_2d, axis=1))

42. Row-wise max: [3 6]


In [105]:
print("43. Column-wise max indices:", np.argmax(arr_2d, axis=0))

43. Column-wise max indices: [1 1 1]


In [106]:
def moving_sum(arr, window=2):
    return np.array([np.sum(arr[i:i+window], axis=0) for i in range(len(arr)-window+1)])
print("44. Moving sum:", moving_sum(arr_2d))

44. Moving sum: [[5 7 9]]


In [107]:
arr_2d = np.array([[2, 4, 6], [8, 10, 12]])
print("45. All even in columns:", np.all(arr_2d % 2 == 0, axis=0))

45. All even in columns: [ True  True  True]


In [108]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("46. Reshaped array:", np.reshape(arr, (2, 3)))

46. Reshaped array: [[1 2 3]
 [4 5 6]]


In [109]:
arr_2d = np.array([[1, 2], [3, 4]])
print("47. Flattened array:", arr_2d.flatten())

47. Flattened array: [1 2 3 4]


In [110]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
print("48. Concatenated array:", np.concatenate((arr1, arr2)))

48. Concatenated array: [1 2 3 4]


In [111]:
print("49. Split arrays:", np.split(arr, 3))

49. Split arrays: [array([1, 2]), array([3, 4]), array([5, 6])]


In [112]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("51. Element-wise addition:", arr1 + arr2)

51. Element-wise addition: [5 7 9]


In [113]:
print("52. Element-wise subtraction:", arr1 - arr2)

52. Element-wise subtraction: [-3 -3 -3]


In [114]:
print("53. Element-wise multiplication:", arr1 * arr2)

53. Element-wise multiplication: [ 4 10 18]


In [115]:
print("54. Element-wise division:", arr1 / arr2)

54. Element-wise division: [0.25 0.4  0.5 ]


In [116]:
print("55. Element-wise exponentiation:", arr1 ** arr2)

55. Element-wise exponentiation: [  1  32 729]


In [117]:
str_arr = np.array(['hello', 'world', 'hello world'])
print("56. Substring 'hello' count:", np.char.count(str_arr, 'hello'))


56. Substring 'hello' count: [1 0 1]


In [118]:
str_arr = np.array(['Hello', 'World', 'Python'])
print("57. Uppercase characters:", np.char.upper(str_arr))

57. Uppercase characters: ['HELLO' 'WORLD' 'PYTHON']


In [119]:
print("58. Replace 'l' with 'x':", np.char.replace(str_arr, 'l', 'x'))


58. Replace 'l' with 'x': ['Hexxo' 'Worxd' 'Python']


In [120]:
str_arr2 = np.array(['!', '!', '!'])
print("59. Concatenated strings:", np.char.add(str_arr, str_arr2))

59. Concatenated strings: ['Hello!' 'World!' 'Python!']


In [121]:
print("60. Longest string length:", np.max(np.char.str_len(str_arr)))

60. Longest string length: 6


In [122]:
rand_arr = np.random.randint(1, 1001, 100)
print("61. Mean:", np.mean(rand_arr), "Median:", np.median(rand_arr),
      "Variance:", np.var(rand_arr), "Std Dev:", np.std(rand_arr))

61. Mean: 496.62 Median: 501.0 Variance: 81660.47559999999 Std Dev: 285.76297100919146


In [123]:
rand_arr = np.random.randint(1, 101, 50)
print("62. 25th and 75th percentiles:", np.percentile(rand_arr, [25, 75]))


62. 25th and 75th percentiles: [35. 77.]


In [124]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([2, 4, 6, 8])
print("63. Correlation coefficient:", np.corrcoef(arr1, arr2))


63. Correlation coefficient: [[1. 1.]
 [1. 1.]]


In [125]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print("64. Matrix multiplication:", np.dot(arr1, arr2))

64. Matrix multiplication: [[19 22]
 [43 50]]


In [126]:
rand_arr = np.random.randint(1, 101, 50)
print("65. Percentiles (10th, 50th, 90th):", np.percentile(rand_arr, [10, 50, 90]),
      "Quartiles:", np.percentile(rand_arr, [25, 50, 75]))

65. Percentiles (10th, 50th, 90th): [17.9 49.  86. ] Quartiles: [26.25 49.   72.5 ]


In [127]:
arr = np.array([1, 2, 3, 4])
print("66. Index of 3:", np.where(arr == 3)[0][0])

66. Index of 3: 2


In [128]:
rand_arr = np.random.randint(1, 100, 5)
print("67. Sorted array:", np.sort(rand_arr))

67. Sorted array: [15 24 59 81 93]


In [129]:
arr = np.array([10, 30, 15, 25])
print("68. Elements > 20:", arr[arr > 20])

68. Elements > 20: [30 25]


In [130]:
print("69. Elements divisible by 3:", arr[arr % 3 == 0])

69. Elements divisible by 3: [30 15]


In [131]:
print("70. Elements between 20 and 40:", arr[(arr >= 20) & (arr <= 40)])

70. Elements between 20 and 40: [30 25]


In [132]:
arr = np.array([1, 2, 3])
print("71. Byte order:", arr.dtype.byteorder)

71. Byte order: =


In [133]:
arr_swapped = arr.byteswap()
print("72. Byte swapped array:", arr_swapped)

72. Byte swapped array: [ 72057594037927936 144115188075855872 216172782113783808]
